opt:
  η: 0.001
train:
  savedir: "models/BCANet-scale2_W1_J1"
  γ: 0.8
  clipnorm: 1e-2
  verbose: false
  W: 1
  β: 0.25
  Δval: 1
  epochs: 500
  Δsched: 5
  δ: 0.5
ckpt: 
net:
  - 10
  - 8
  - 7
  - 2
  - 1e-1
data:
  params:
    σ: 1
    batch_size: 1
    J: 1
    crop_size: 400
    gray: true
    scale: 2
  root: "MPI_Sintel/"
