opt:
  η: 8e-5
train:
  savedir: "models/PiBCANet-test"
  γ: 0.95
  clipnorm: 1
  stopgrad: true
  verbose: true
  β: 5
  Δval: 2
  epochs: 20
  Δsched: 2
  δ: 0.5
ckpt: 
net:
  W: 5          # Warps per scale
  shared: true  # BCANet sharing
  K: 10         # itrs per module
  M: 4         # num filters
  P: 6          # filter side length
  s: 2          # stride
  λ₀: 1e-1      # initial threshold
data:
  params:
    σ: 1
    batch_size: 2
    J: 1
    crop_size: 256
    gray: true
    scale: 2
  root: "dataset/MPI_Sintel/"
