opt:
  η: 1e-4
train:
  α: 3
  Δval: 2
  Δsched: 5
  clipvalue: 1.0
  weight_decay: 0.0001
  verbose: true
  δ: 1.05
  clipnorm: false
  β: 1.25
  savedir: "models/PiBCANet-test"
  γ: 0.95
  stopgrad: true
  epochs: 20
ckpt: 
net:
  shared_iter: false
  shared_scale: false
  P: 5
  M: 16
  s: 1
  W: 5
  J: 5
  K: 10
  λ₀: 1e-3
data:
  params:
    σ: 0.01
    batch_size: 1
    J: 5
    crop_size: 368
    scale: 0
  root: "dataset/MPI_Sintel/"
  gray: true
