opt:
  η: 1e-4
train:
  savedir: "models/PiBCANet-test"
  γ: 0.95
  clipnorm: 1
  stopgrad: true
  verbose: true
  β: 5
  α: 1
  Δval: 2
  epochs: 10
  Δsched: 100
  δ: 0.5
  weight_decay: 0
ckpt: 
net:
  W: 1          # Warps per scale
  shared: false # BCANet sharing
  K: 20         # itrs per module
  M: 4          # num filters
  P: 5          # filter side length
  s: 1          # stride
  λ₀: 1e-1      # initial threshold
data:
  params:
    σ: 1
    batch_size: 1
    J: 2
    crop_size: 64
    scale: 0
  root: "dataset/MPI_Sintel/"
  gray: true
