opt:
  η: 0.1
train:
  savedir: "models/BCANet-test"
  γ: 0.95
  clipnorm: 1e-2
  verbose: true
  W: 0
  β: 0.5
  Δval: 1
  epochs: 3
  Δsched: 1
  δ: 0.5
  β: 0.5
ckpt: 
net:
  - 10
  - 8
  - 5
  - 2
  - 1e-1
data:
  params:
    σ: 1
    batch_size: 4
    J: 1
    crop_size: 256
    gray: true
    scale: 1
  root: "/home/nikopj/dataset/MPI_Sintel/"
