opt:
  η: 1e-3
train:
  α: 0.5
  Δval: 5
  Δsched: 10
  clipvalue: 1.0
  weight_decay: 1e-5
  verbose: true
  δ: 1.5
  clipnorm: false
  β: 1.25
  savedir: "models/PiBCANet-test"
  γ: 0.95
  stopgrad: true
  epochs: 20
  use_mask: false
  gt_init: false
  maxiter: 50
  Loss: "EPE"
ckpt: 
net:
  classical_init: false
  shared_iter: false
  shared_scale: false
  P: 5
  M: 8
  s: 1
  W: 0
  J: 0
  K: 10
  λ₀: 1e-1
data:
  dataset: "FlyingChairs"
  root: "dataset/FlyingChairs/"
  ds_params:
    gray: true
    flomax: 32
  dl_params:
    σ: [1e-3, 5e-1]
    batch_size: 2
    J: 0
    crop_size: 256
    scale: 5
