opt:
  η: 1e-3
train:
  α: 1
  Δval: 2
  Δsched: 5
  clipvalue: 1.0
  weight_decay: 0.0001
  verbose: true
  δ: 1.2
  clipnorm: false
  β: 1.25
  savedir: "models/PiBCANet-test"
  γ: 0.95
  stopgrad: true
  epochs: 10
  use_mask: false
  gt_init: false
  maxiter: 10
ckpt: 
net:
  shared_iter: false
  shared_scale: false
  P: 3
  M: 4
  s: 1
  W: 0
  J: 0
  K: 3
  λ₀: 1e-2
data:
  dataset: "FlyingChairs"
  params:
    σ: 1
    batch_size: 1
    J: 0
    crop_size: 256
    scale: 0
  root: "dataset/FlyingChairs/"
  gray: true
