loop:
  Loss: ["EPE", "L1"]
  η: [1e-3, 1e-4]
  weight_decay: [1e-4, 0] 
  classical_init: [true, false]
name: "PiBCANet-tanh_init_decay_loss_lr"
version0: 1
args:
  opt:
    η: 1e-3
  train:
    savedir: 
    γ: 0.5
    clipnorm: false
    clipvalue: 1.0
    stopgrad: true
    verbose: false
    β: 1.25
    α: 1
    Δval: 5
    epochs: 1000
    Δsched: 200
    δ: 1.5
    weight_decay: 1e-4
    use_mask: false
    gt_init: false
    maxiter: 100
    Loss: "EPE"
  ckpt: 
  net:
    classical_init: false
    W: 0          # Warps per scale
    shared_iter: false 
    shared_scale: false
    J: 5
    K: 20         # itrs per module
    M: 16         # num filters
    P: 5          # filter side length
    s: 1          # stride
    λ₀: 1e-1      # initial threshold
  data:
    dataset: "FlyingChairs"
    root: "dataset/FlyingChairs/"
    ds_params:
      gray: true
      flomax: 512
    dl_params:
      σ: [1e-3, 5e-1]
      batch_size: 8
      J: 5
      crop_size: 256
      scale: 0
