loop: 
  η: [1e-3, 1e-4]
  weight_decay: [1e-4, 1e-6, 0] 
name: "PiBCANet-lr_decay_W=1_K=10"
version0: 1
args:
  opt:
    η: 1e-3
  train:
    savedir: 
    γ: 0.5
    clipnorm: false
    clipvalue: 1.0
    stopgrad: true
    verbose: false
    β: 1.25
    α: 1
    Δval: 5
    epochs: 200
    Δsched: 25
    δ: 1.1
    weight_decay: 1e-4
    use_mask: false
    gt_init: false
    maxiter: 1000
  ckpt: 
  net:
    classical_init: false
    W: 1          # Warps per scale
    shared_iter: false 
    shared_scale: false
    J: 5
    K: 10         # itrs per module
    M: 16         # num filters
    P: 5          # filter side length
    s: 1          # stride
    λ₀: 1e-2      # initial threshold
  data:
    dataset: "FlyingChairs"
    params:
      σ: 5e-1
      batch_size: 6
      J: 5
      crop_size: 256
      scale: 0
    root: "dataset/FlyingChairs/"
    gray: true
